name: Test and Build

on:
  push:
    branches:
      - main # Solo para pruebas
  pull_request:
    branches:
      - main 

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.3

    - name: Install dependencies
      run: go mod download

    - name: Compile
      run: CGO_ENABLED=0 go build -o /dev/null .
  test:    
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.3
      - name: Install dependencies
        run: go mod download   
      - name: Test
        run: go test -v ./... -coverprofile=coverage
      - name: Show coverage
        run: go tool cover -func=coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage
          flags: unittests
          name: codecov
          fail_ci_if_error: false
  