name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'  # Semver pattern (e.g., 1.0.3)

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
            tag_name: ${{ github.ref_name }}
            token: ${{ secrets.GITHUB_TOKEN }}
            draft: false
            prerelease: false
            generate_release_notes: true 
  build:
    name: Build on ${{ matrix.os }} (${{ matrix.arch }}) with ${{ matrix.tag }} tag
    runs-on: ubuntu-latest
    needs: create_release
    env:
      BINARY_NAME: builder-cli
    strategy:
      matrix:
        os: [linux, windows]
        tag: [free]
        arch: [amd64]
        include:
          - os: windows
            extension: .exe
          - os: linux
            extension: ''
          - tag : free
            suffix: ''
          - tag : pro
            suffix: '-pro'            
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.3

      - name: Install dependencies
        run: go mod download

      - name: Build Binary
        run: CGO_ENABLED=0 GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o ${{ env.BINARY_NAME}}-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.suffix }}${{ matrix.extension }} -tags ${{ matrix.tag }} .

      - name: Upload ${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.tag }} binary to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./${{ env.BINARY_NAME}}-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.suffix }}${{ matrix.extension }}
          asset_name: ${{ env.BINARY_NAME}}-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.suffix }}${{ matrix.extension }}
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}