name: Build and Release

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.3

    - name: Install dependencies
      run: go mod download

    - name: Build Linux binary
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o builder-cli-linux .
      
    - name: Build Windows binary
      run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o builder-cli-windows.exe .

    - name: Generate changelog
      run: |
        docker run --rm -v "$(pwd)":/usr/local/src/ \
        -e CHANGELOG_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
        githubchangeloggenerator/github-changelog-generator \
        -u ${{ github.repository_owner }} \
        -p ${{ github.event.repository.name }} \
        -o /usr/local/src/CHANGELOG.md
    - name: List files in current directory
      run: ls -la

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
          #body_path: ${{ github.workspace }}/CHANGELOG.md
          tag_name: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false

    - name: Upload Linux binary to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./builder-cli-linux
        asset_name: builder-cli-linux
        asset_content_type: application/octet-stream

    - name: Upload Windows binary to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./builder-cli-windows.exe
        asset_name: builder-cli-windows.exe
        asset_content_type: application/octet-stream
