name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'  # Semver pattern (e.g., 1.0.3)

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download builder-cli-linux from artifacts
      uses: actions/download-artifact@v2
      with:
        name: builder-cli-linux
        path: ./builder-cli-linux

    - name: Download builder-cli-windows.exe from artifacts
      uses: actions/download-artifact@v2
      with:
        name: builder-cli-windows.exe
        path: ./builder-cli-windows.exe

    - name: Generate changelog
      run: |
        docker run --rm -v "$(pwd)":/usr/local/src/ \
        -e CHANGELOG_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
        githubchangeloggenerator/github-changelog-generator \
        -u ${{ github.repository_owner }} \
        -p ${{ github.event.repository.name }} \
        --since-tag ${{ github.ref_name }} \
        --due-tag ${{ github.ref_name }} \
        --unreleased-label ${{ github.ref_name }} \
        --include-tags-regex "${{ github.ref_name }}" \
        -o /usr/local/src/CHANGELOG.md
    
    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
          tag_name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          generate_release_notes: true


    - name: Upload Linux binary to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./builder-cli-linux
        asset_name: builder-cli-linux
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Windows binary to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./builder-cli-windows.exe
        asset_name: builder-cli-windows.exe
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
