name: Test and Build

on:
  push:
    branches:
      - main # Solo para pruebas
  pull_request:
    branches:
      - main 

jobs:
  test:    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.3
      - name: Install dependencies
        run: go mod download   
      - name: Test
        run: go test -v ./... -coverprofile=coverage
      - name: Show coverage
        run: go tool cover -func=coverage
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.3

    - name: Install dependencies
      run: go mod download

    - name: Build Linux binary
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /dev/null .
      
    - name: Build Windows binary
      run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o /dev/null .